# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-05 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=128)),
                ('avatar_url', models.CharField(max_length=128)),
                ('gender', models.IntegerField()),
                ('language', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('isbn', models.CharField(max_length=128)),
            ],
        ),
    ]
