# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-05 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('translator', models.CharField(max_length=64)),
                ('publisher', models.CharField(max_length=32)),
                ('img', models.CharField(max_length=128)),
                ('rate', models.FloatField(max_length=0)),
                ('isbn', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_isbn', models.CharField(max_length=64)),
                ('latitude', models.FloatField(max_length=0)),
                ('longitude', models.FloatField(max_length=0)),
                ('altitude', models.IntegerField()),
                ('vertical_accuracy', models.IntegerField()),
                ('horizontal_accuracy', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('create_datetime', models.DateTimeField()),
                ('book_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='isbn',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(max_length=32),
        ),
        migrations.AddField(
            model_name='bookuser',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
