# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-05 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171206_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookuser',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
