# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-05 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171206_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='create_datetime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
