# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-06 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171206_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
