# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-08 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171209_0100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookuser',
            unique_together=set([('book', 'user')]),
        ),
    ]
