# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171209_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
