# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171209_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
