# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_open_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='open_id',
            field=models.CharField(max_length=28, null=True),
        ),
    ]
