# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-01 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171215_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(default=0, null=True)),
                ('content', models.TextField(max_length=512)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('book', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Book')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.CharField(max_length=128, null=True)),
                ('like_count', models.IntegerField(default=0, null=True)),
                ('content', models.TextField(max_length=512)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('article', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Article')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='FollowRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('followee', models.ManyToManyField(related_name='followee', to='api.User')),
                ('follower', models.ManyToManyField(related_name='follower', to='api.User')),
            ],
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Book'),
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User'),
        ),
    ]
