# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-01 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180101_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrelations',
            name='followee',
        ),
        migrations.AddField(
            model_name='followrelations',
            name='followee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followee', to='api.User'),
        ),
        migrations.RemoveField(
            model_name='followrelations',
            name='follower',
        ),
        migrations.AddField(
            model_name='followrelations',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to='api.User'),
        ),
    ]
